### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [LemonRiz/lemonriz.github.io#1]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages) : DONE
2. A public GitHub repository for your codebase : DONE
3. Use HTML & SCSS : DONE
4. Make good use of semantic HTML elements : DONE
5. Be responsive (mobile-first) and built with accessibility in mind : DONE
6. Code is highly readable (good naming and indented correctly) : DONE - Needs work

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Augusta-Course-Resources/blob/main/student-resources/00-slides/01-web/marking-scheme.md)

| Category             | Score   |
| -------------------- | ------- |
| Site Output          | 30 / 50 |
| Responsiveness       | 10 / 15 |
| Code Knowledge & Use | 15/ 20  |
| Readability          | 10 / 15 |
| Version Control      | 10/ 10  |
| Total Score          | 75/ 110 |

## Positive

As your first project I think that this is a success, you have clearly enjoyed coding a website from a wire frame and been able to apply what we have learnt. If you ever need a break pick a section from a website and try and recreate it.

The website looks great on mobile, and almost matches the design. There are a couple of tweaks you will need to make mainly around spacing on desktop. Everything feels pretty squished so make use of padding and margin to add space between your html elements. Your footer needs a little bit of attention.

```scss
footer {
  // OTHER STYLES HERE
  li {
    background-color: white;
    border-radius: 100%;
    // TO GET THE ICONS INTO THE CENTRE OF THE CIRCLES
    display: flex;
    justify-content: center;
    align-items: center;
  }
}
```

You have started to customize the project which is great!

- This is a good place to play around with adding functionality with JS!

Great use of Git and Github, keep on committing with meaningful messages.

You are demonstrating a solid understanding of the majority of topics we have covered so far, keep it up and keep on using BEM, SCSS, grid and flex :D.

## Constructive

- I like your tattoo but your portfolio wont be the place to show it off, I understand it is probably just a placeholder.

- You have 12 `<h1>'s`, you should only have one [w3](https://www.w3schools.com/tags/tag_hn.asp), this would be for the main title of the page.

- You may have relied on the grid generator a little bit to much, don't get me wrong it is a great tool but for a simple grid it has over complicated some of your styles. You shouldn't need grid `grid-area` unless you have a complicated grid.

```scss
&__grid1 {
  // START AT COLUMN & ROW ONE GO TO COLUMN & ROW 2
  grid-area: 1 / 1 / 2 / 2;
  // GRID WILL DO THIS FOR YOU
}
```

- Your BEM is a bit hit and miss which is fine as it takes practice.

  - names are lowercase hyphenated if multiple words. Camel casing is for JS.
    - e.g. `techSkills` -> `tech-skills`
  - The class name should describe what it is, generally you wouldn't use the tag name in the class. Keep it descriptive

Lets compare HTML.

```html
<section id="skillsSection" class="skills">
  <h1 class="skills__h1">Technical Skills</h1>
  <p class="skills__p">
    Maecenas accumsan tincidunt id et in ut diam sit. Metus, nec, augue urna gravida nisl, tortor sapien nec
    sollicitudin.
  </p>
  <div class="techSkills">
    <div class="techSkills__grid1">
      <img class="TechSkills__pic" src="./images/html5.png" />
      <p>HTML5</p>
    </div>
    <!-- OTHER ITEMS HERE -->
  </div>
</section>
<!-- WOULD BE  -->
<section id="skillsSection" class="skills">
  <h1 class="skills__title">Technical Skills</h1>
  <p class="skills__text">
    Maecenas accumsan tincidunt id et in ut diam sit. Metus, nec, augue urna gravida nisl, tortor sapien nec
    sollicitudin.
  </p>
  <div class="skills__list">
    <!-- IF YOU DID HAVE A NAME THAT IS TWO WORDS -->
    <!-- ALSO IF YOU NEEDED A MODIFIER -->
    <div class="skills__list-item skills__list-item--1">
      <img class="skills__img" src="./images/html5.png" />
      <p>HTML5</p>
    </div>
    <!-- OTHER ITEMS HERE -->
  </div>
</section>
```

Lets compare SCSS.

```scss
.skills {
  display: flex;
  flex-direction: column;
  align-items: center;
  // border: solid 2px green;
  &__h1 {
    align-self: center;
  }
  &__p {
    text-align: center;
  }
}

.techSkills {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  grid-template-rows: repeat(3, 1fr);
  grid-column-gap: 2rem;
  grid-row-gap: 0.5rem;
  text-align: center;

  &__grid1 {
    grid-area: 1 / 1 / 2 / 2;
  }
  &__grid2 {
    grid-area: 1 / 2 / 2 / 3;
  }
  &__grid3 {
    grid-area: 1 / 3 / 2 / 4;
  }
  &__grid4 {
    grid-area: 2 / 1 / 3 / 2;
  }
  &__grid5 {
    grid-area: 2 / 2 / 3 / 3;
  }
  &__grid6 {
    grid-area: 2 / 3 / 3 / 4;
  }
  &__grid7 {
    grid-area: 3 / 1 / 4 / 2;
  }
  &__grid8 {
    grid-area: 3 / 2 / 4 / 3;
  }
  &__grid9 {
    grid-area: 3 / 3 / 4 / 4;
  }
}

// WOULD BE

.skills {
  display: flex;
  flex-direction: column;
  align-items: center;

  &__title {
    align-self: center;
  }

  &__text {
    text-align: center;
  }

  &__list {
    // YOU CAN SET YOUR GRID HERE & LET IT DO ALL OF THE LAYING OUT.
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: repeat(3, 1fr);
    grid-column-gap: 2rem;
    grid-row-gap: 0.5rem;
    text-align: center;
  }

  &__list-item {
    // IF YOU NEEDED TO USE A MODIFIER
    &--1 {
      // THE GRID AREAS ON THE IMG'S CAN BE REMOVED AS THEY AREN'T DOING ANYTHING.
    }
  }
}
```

I want you to take these points further with your next project, use SCSS and the awesome features it gives you. Try using BEM for naming as well.

Reach out if you do run into any problems.

---
